# Generated by Django 3.0.5 on 2021-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_path_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='Exp'),
        ),
    ]
