# Generated by Django 3.0 on 2021-05-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_path_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
